package ua.in.sz.jcurses.event;

import ua.in.sz.jcurses.widgets.Widget;

/**
*  Instances of this class are generated by widgets if an user makes an action,
*  for example pushes a button or selects a menu item.
*/
public class ActionEvent extends Event {
	
	public ActionEvent(Widget source) {
		super(source);
	}

}
